language: node_js

node_js:
  - lts/*

branches:
  only:
    - master
    - beta
    - production

cache: yarn

install:
  - yarn install --frozen-lockfile
  - yarn pre-ci || travis_terminate 1
  - yarn postinstall
  - git --no-pager diff HEAD --exit-code || travis_terminate 1 # This makes sure that someone ran "yarn install" after merging their PR, and that the postinstall doesn't produce any diffs, which are annoying/confusing

before_script:
  - yarn prettier

matrix:
  include:
    - name: 'Common Pipeline'
      env:
        - PACKAGE_LOCATION=packages/common
        - PACKAGE_NAME=common
        - SITE_NAME=script-lab-react-common

    - name: 'Editor Pipeline'
      env:
        - PACKAGE_LOCATION=packages/editor
        - PACKAGE_NAME=editor
        - SITE_NAME=script-lab-react

    - name: 'Runner Pipeline'
      env:
        - PACKAGE_LOCATION=packages/runner
        - PACKAGE_NAME=runner
        - SITE_NAME=script-lab-react-runner

    - name: 'Server Pipeline'
      env:
        - PACKAGE_LOCATION=packages/server
        - PACKAGE_NAME=server
        - SITE_NAME=script-lab-react-server

script:
  - cd $PACKAGE_LOCATION
  - yarn lint || travis_terminate 1
  - yarn test || travis_terminate 1
  - yarn build || travis_terminate 1
  - cd $TRAVIS_BUILD_DIR
  - if [[ "$TRAVIS_PULL_REQUEST" == false ]]; then yarn deploy; fi

env:
  global:
    - HTTPS=true
